apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupid-busybox-deployment
spec:
  selector:
    matchLabels:
      app: groupidbusybox
  replicas: 1
  template:
    metadata:
      labels:
        app: groupidbusybox
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: groupidbusybox
        image: busybox:1.28
        command: [ "sh", "-c", "sleep 30d" ]
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          allowPrivilegeEscalation: false