apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnetwork-busybox-deployment
spec:
  selector:
    matchLabels:
      app: hostnetworkbusybox
  replicas: 1
  template:
    metadata:
      labels:
        app: hostnetworkbusybox
    spec:
      hostNetwork: true
      containers:
      - name: hostnetworkbusybox
        image: busybox:1.28
        command: ["sh", "-c", "sleep 30d"]
        ports:
        - containerPort: 8080