apiVersion: apps/v1
kind: Deployment
metadata:
  name: latestimagetag-nginx-deployment
spec:
  selector:
    matchLabels:
      app: latestimagetagnginx
  replicas: 1
  template:
    metadata:
      labels:
        app: latestimagetagnginx
    spec:
      containers:
      - name: latestimagetagnginx
        image: nginx:latest
        ports:
        - containerPort: 80