apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-nginx-deployment
spec:
  selector:
    matchLabels:
      app: privilegednginx
  replicas: 1
  template:
    metadata:
      labels:
        app: privilegednginx
    spec:
      containers:
      - name: privilegednginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
