apiVersion: apps/v1
kind: Deployment
metadata:
  name: seccomp-disabled-nginx-deployment
spec:
  selector:
    matchLabels:
      app: seccompdisablednginx
  replicas: 1
  template:
    metadata:
      labels:
        app: seccompdisablednginx
    spec:
      containers:
      - name: seccompdisablednginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        securityContext:
          seccompProfile:
            type: Unconfined