apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
spec:
  selector:
    matchLabels:
      app: webgoat
  replicas: 1
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: public.ecr.aws/g9n7f0y2/scbcontainerpov:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"